version: "3"
services:
  sonarqube:
    image: sonarqube
    container_name: sonar
    ports:
      - "9000:9000"
    networks:
      sonarnet:
        ipv4_address: 172.19.0.14
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
  node:
    image: node:latest
    container_name: metrics_manager
    environment:
      - COVERAGE_CEILING=85
      - GATE_ID_COVERAGE=6
      - GUEST_PORT=3000
      - SONAR_HOST=172.19.0.14
      - SONAR_PASSWORD=admin
      - SONAR_PORT=9000
      - SONAR_USERNAME=admin
    ports:
      - "3000:3000"
    volumes:
      - ./src/node:/node
      - ./node_modules:/node/node_modules
    command: /node/node_modules/.bin/nodemon /node/index.js
    networks:
      sonarnet:
        ipv4_address: 172.19.0.15
  db:
    image: postgres
    container_name: sonar_pg_db
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
        # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
  node_modules: